### PR TITLE
BioHackathon24

### PR DESCRIPTION
**Pull request by CFGrote**
This PR (WIP) adds all developments from the biohackathon2024 into the main branch. 

- Mappings for the muenster .137 in *hack24\/*
- Mappings for the MPI ome instance in *MPIEB\/*
- added a test that checks class matching against another ontology via `owl:equivalentClass` works correctly
- small cleanups and typos.

- Adding ontop artifacts for hackathon.
- Update mapping and properties.
- Update all in hack24
- Update props.
- untrack cataloge.
- Ignore catalog file in hack24.
- Fixing project mappings
- Update mappings
- Update mappings
- Debug mappings.
- Update ontology.
- Update test
- Fix indent.
- Add query against the MPIEB OME KG
- Adding mapping and ontology geared towards mpieb.

### CODE REVIEW

**Comment by CFGrote** [comment]
@joshmoore , @marimeireles, maybe one of you can give this a look and merge.

**Comment by joshmoore** [comment]
What's the plan for the "hack24" directory long term? i.e. will those items be integrated elsewhere?

**Comment by joshmoore** [comment]
@CFGrote: what happened here? I now no longer see the hack24/ code.

**Comment by CFGrote** [comment]
yeah sorry for being impatient . I merged this one to be able to continue on other stuff. All mappings are now in *ontop\/*, no separate directories for the various omero instances anymore. The hack24 mappings are preserved in *ontop\/hack24.obda*. Hope that's ok.

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
